"""
Writes all workflow outputs to the output/ directory:
  - account_briefings.json / account_briefings.md (ranked by risk)
  - quality_review_report.json / quality_review_report.md
  - token_usage_log.csv (every simulated LLM call, metered)
  - workflow_summary.md (top-level run summary)
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import List

from src import config
from src.briefing_generator import AccountBriefing
from src.llm_simulator import SimulatedLLMClient
from src.quality_reviewer import QualityReview


def _ensure_output_dir() -> None:
    config.LEGACY_STAGE_REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def write_token_usage_log(client: SimulatedLLMClient) -> Path:
    _ensure_output_dir()
    path = config.LEGACY_STAGE_REPORTS_DIR / "token_usage_log.csv"
    fieldnames = [
        "timestamp", "task", "reference_id", "model",
        "prompt_tokens", "completion_tokens", "total_tokens", "estimated_cost_usd",
    ]
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for record in client.call_log:
            writer.writerow(record.as_row())
    return path


def write_account_briefings(briefings: List[AccountBriefing]) -> Path:
    _ensure_output_dir()

    json_path = config.LEGACY_STAGE_REPORTS_DIR / "account_briefings.json"
    json_data = [
        {
            "account_id": b.account_id,
            "account_name": b.account_name,
            "csm_owner": b.csm_owner,
            "priority_tier": b.priority_tier,
            "risk_score": b.risk_score,
            "opportunity_score": b.opportunity_score,
            "summary": b.summary,
            "risk_and_opportunity_notes": b.risk_and_opportunity_notes,
            "recommended_actions": b.recommended_actions,
        }
        for b in briefings
    ]
    json_path.write_text(json.dumps(json_data, indent=2), encoding="utf-8")

    md_path = config.LEGACY_STAGE_REPORTS_DIR / "account_briefings.md"
    lines = ["# Account Briefings — Ranked by Risk\n"]
    lines.append(
        "Generated by a simulated LLM call per account (deterministic logic; "
        "no external API used). Sorted highest risk first.\n"
    )
    for rank, b in enumerate(briefings, start=1):
        lines.append(f"## {rank}. {b.account_name} ({b.account_id}) — {b.priority_tier} priority\n")
        lines.append(f"- **CSM owner:** {b.csm_owner}")
        lines.append(f"- **Risk score:** {b.risk_score} | **Opportunity score:** {b.opportunity_score}\n")
        lines.append(f"**Summary:** {b.summary}\n")
        lines.append("**Risk / opportunity notes:**")
        for note in b.risk_and_opportunity_notes:
            lines.append(f"- {note}")
        lines.append("\n**Recommended actions:**")
        for action in b.recommended_actions:
            lines.append(f"- {action}")
        lines.append("")
    md_path.write_text("\n".join(lines), encoding="utf-8")

    return md_path


def write_quality_review_report(reviews: List[QualityReview]) -> Path:
    _ensure_output_dir()

    json_path = config.LEGACY_STAGE_REPORTS_DIR / "quality_review_report.json"
    json_data = [
        {
            "output_id": r.output_id,
            "account_id": r.account_id,
            "output_type": r.output_type,
            "draft_text": r.draft_text,
            "intended_customer_action": r.intended_customer_action,
            "overall_score": r.overall_score,
            "recommendation": r.recommendation,
            "suggested_revision": r.suggested_revision,
            "standard_verdicts": [
                {
                    "standard_id": v.standard_id,
                    "standard_name": v.standard_name,
                    "verdict": v.verdict,
                    "rationale": v.rationale,
                }
                for v in r.standard_verdicts
            ],
        }
        for r in reviews
    ]
    json_path.write_text(json.dumps(json_data, indent=2), encoding="utf-8")

    md_path = config.LEGACY_STAGE_REPORTS_DIR / "quality_review_report.md"
    lines = ["# Junior Output Quality Review\n"]
    lines.append(
        "Generated by a simulated LLM-as-judge call per output (deterministic, "
        "rule-based heuristics; no external API used).\n"
    )
    for r in reviews:
        lines.append(f"## {r.output_id} ({r.account_id}) — {r.output_type}\n")
        lines.append(f"> \"{r.draft_text}\"\n")
        lines.append(f"**Intended action:** {r.intended_customer_action}\n")
        lines.append("**Standard verdicts:**")
        for v in r.standard_verdicts:
            lines.append(f"- **[{v.standard_id}] {v.standard_name} — {v.verdict}**: {v.rationale}")
        lines.append(f"\n**Overall score:** {r.overall_score}/100 → **{r.recommendation}**")
        if r.suggested_revision:
            lines.append(f"\n{r.suggested_revision}")
        lines.append("")
    md_path.write_text("\n".join(lines), encoding="utf-8")

    return md_path


def write_workflow_summary(briefings: List[AccountBriefing], reviews: List[QualityReview],
                            client: SimulatedLLMClient, validation_notes: List[str]) -> Path:
    _ensure_output_dir()
    path = config.LEGACY_STAGE_REPORTS_DIR / "workflow_summary.md"

    tier_counts = {"High": 0, "Medium": 0, "Low": 0}
    for b in briefings:
        tier_counts[b.priority_tier] += 1

    rec_counts = {"Approved": 0, "Needs revision": 0, "Rejected": 0}
    for r in reviews:
        rec_counts[r.recommendation] += 1

    cost_summary = client.summary()

    lines = ["# Customer Success AI Workflow — Run Summary\n"]
    lines.append("## Data validation")
    if validation_notes:
        for n in validation_notes:
            lines.append(f"- {n}")
    else:
        lines.append("- All 7 input files loaded and validated successfully; all required columns present.")

    lines.append("\n## Stage 1 — Account Briefings")
    lines.append(f"- Accounts processed: {len(briefings)}")
    lines.append(f"- Priority tiers: High={tier_counts['High']}, Medium={tier_counts['Medium']}, Low={tier_counts['Low']}")
    if briefings:
        top = briefings[0]
        lines.append(f"- Top-priority account: **{top.account_name}** ({top.account_id}), risk score {top.risk_score}")

    lines.append("\n## Stage 2 — Quality Review")
    lines.append(f"- Outputs reviewed: {len(reviews)}")
    lines.append(
        f"- Recommendations: Approved={rec_counts['Approved']}, "
        f"Needs revision={rec_counts['Needs revision']}, Rejected={rec_counts['Rejected']}"
    )

    lines.append("\n## Simulated LLM usage & cost (no external API calls made)")
    lines.append(f"- Model label: {cost_summary['model']}")
    lines.append(f"- Total simulated calls: {cost_summary['total_calls']}")
    lines.append(
        f"- Tokens: {cost_summary['total_prompt_tokens']} prompt + "
        f"{cost_summary['total_completion_tokens']} completion = {cost_summary['total_tokens']} total"
    )
    lines.append(f"- Estimated cost: ${cost_summary['total_estimated_cost_usd']:.6f}")
    lines.append("\nSee `token_usage_log.csv` for the per-call breakdown.")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path
